    # -- Default styles for "CGLipidBr2005" --
    units           real
    atom_style      full
    # (Hybrid force field styles were used for portability.)
    bond_style      hybrid harmonic

    #angle_style     hybrid cosine/delta # <- used in the original article
    angle_style     hybrid harmonic  # <- prevents unphysical acute angle turns
    # Explanation:
    # angle_style cosine/delta:  U(theta) = k*(1-cos(theta-theta0))
    # angle_style     harmonic:  U(theta) = k*(theta-theta0)^2

    dihedral_style  none
    pair_style  hybrid table linear 1130 &
                lj/charmm/coul/charmm/inter es4k4l 14.5 15
    pair_modify     mix arithmetic
    special_bonds   lj 0.0 0.0 1.0   # turn off pairs if "less than 3 bonds"

    neighbor 2.0 multi  # <- perhaps unnecessary
    #communicate multi   # <- perhaps unnecessary
    #comm_style brick
    #comm_modify mode multi
    units           real
    atom_style      full
    bond_style      hybrid harmonic
    angle_style     hybrid harmonic
    dihedral_style  hybrid fourier
    pair_style hybrid lj/charmm/coul/charmm/inter es4k4l maxmax 21.0 24.0
    pair_modify     mix arithmetic
    special_bonds   lj 0.0 0.0 1.0   #(turn on "1-4" interactions)
  # -- These styles override earlier settings --
  units           real
  atom_style      full
  # (Hybrid force field styles were used for portability.)
  bond_style      hybrid harmonic
  angle_style     hybrid cosine/delta harmonic
  dihedral_style  hybrid fourier
  pair_style  hybrid table linear 1130 lj/charmm/coul/charmm/inter es4k4l 14.5 15
  pair_modify     mix arithmetic
  special_bonds   lj 0.0 0.0 1.0   # turn off pairs if "less than 3 bonds"
